"""The native core (native/, the renderer for Godot) against the Python reference: same random numbers, same sound.
Skipped unless it is built: python tools/build_native.py build (or point TARE_TOOLS_TUNE_NATIVE at the library)."""
import ctypes
import json
import os
import platform
import re
from ctypes import POINTER, c_char_p, c_double, c_float, c_int32, c_int64, c_uint8, c_uint64, c_void_p
from pathlib import Path

import numpy as np
import pytest

from tare.tools.tune import ARCHETYPES, RECIPES, Creature, Sfx, Voice, rng
from tare.tools.tune.music import Cue
from tare.tools.tune.render import render
from tare.tools.tune.spec import Modal, Noise, Scatter, Syllable
from tare.tools.tune.speech import Speaker, concat

NAME = {"Windows": "tare_tune.dll", "Darwin": "libtare_tune.dylib"}.get(platform.system(), "libtare_tune.so")
NATIVE = Path(__file__).parent.parent / "native"
PATH = Path(os.environ.get("TARE_TOOLS_TUNE_NATIVE", NATIVE / "build" / NAME))
built = pytest.mark.skipif(not PATH.exists(), reason="the native core is not built")


def test_the_native_constants_are_the_python_ones():
    """native/src/tables.hpp, generated by tools/build_native.py tables: still what the vocoder computes."""
    from tare.tools.tune.speech.vocoder import ap_freqs, band_freqs
    text = (NATIVE / "src" / "tables.hpp").read_text(encoding="utf-8")
    tables = {m[0]: np.array([float.fromhex(v) for v in m[1].split(",")])
              for m in re.findall(r"double (\w+)\[\d+\] = \{([^}]*)\}", text)}
    expected = {"BAND_FREQS_32": band_freqs(32), "BAND_FREQS_64": band_freqs(64), "LOG_AP_FREQS": np.log(ap_freqs()),
                **{f"DC_{n}": np.hanning(n // 2) / np.hanning(n // 2).sum() for n in (1024, 2048)}}
    assert tables.keys() == expected.keys()
    for name, values in expected.items():
        assert np.allclose(tables[name], values, rtol=1e-12, atol=0), name


def test_a_voice_bank_file_holds_the_same_frames(tmp_path):
    from tare.tools.tune.speech import tvb
    path = tvb.export("pt/dora", tmp_path / "pt_dora.tvb")
    header, frames = tvb.read(path)
    b = concat.bank("pt/dora")
    assert header["name"] == "pt/dora" and header["frames"] == len(b.f0) and header["bands"] == 64
    assert path.stat().st_size < 25e6                      # about the size of the .npz it comes from
    assert np.array_equal(frames["f0"], b.f0.astype(np.float32)) and np.array_equal(frames["f0"], b.f0)
    assert np.array_equal(frames["env"], b._env8)
    assert np.array_equal(frames["ap"].astype(np.float32) / 255, b.ap)


@pytest.fixture(scope="module")
def lib():
    lib = ctypes.CDLL(str(PATH))
    lib.tt_bank_new.restype = c_void_p
    lib.tt_bank_new.argtypes = [c_int32, c_int32, POINTER(c_float), POINTER(c_uint8), POINTER(c_uint8)]
    lib.tt_bank_free.argtypes = [c_void_p]
    lib.tt_key.restype = c_uint64
    lib.tt_key.argtypes = [c_uint64, c_char_p, c_int64]
    lib.tt_render_spoken.restype = c_int32
    lib.tt_render_spoken.argtypes = [c_void_p, POINTER(c_double), c_int32, POINTER(c_int32), c_int32,
                                     POINTER(c_double), c_int32, c_double, c_double, c_double, c_double, c_uint64,
                                     c_int32, POINTER(POINTER(c_double)), POINTER(c_int32)]
    lib.tt_render_voice.restype = c_int32
    lib.tt_render_voice.argtypes = [c_char_p, c_char_p, POINTER(c_void_p), POINTER(c_char_p), c_int32, c_int32,
                                    POINTER(POINTER(c_float)), POINTER(c_int32)]
    lib.tt_last_error.restype = c_char_p
    lib.tt_free.argtypes = [c_void_p]
    return lib


@pytest.fixture(scope="module")
def banks(lib):
    out = {}
    for name in concat.banks("pt"):
        b = concat.bank(name)
        f0 = np.ascontiguousarray(b.f0, np.float32)                  # stored as float16: exact in float32
        env = np.ascontiguousarray(b._env8, np.uint8)
        ap = np.ascontiguousarray(np.round(b.ap * 255), np.uint8)
        out[name] = (lib.tt_bank_new(len(f0), env.shape[1], f0.ctypes.data_as(POINTER(c_float)),
                                     env.ctypes.data_as(POINTER(c_uint8)), ap.ctypes.data_as(POINTER(c_uint8))),
                     (f0, env, ap))
    yield {name: handle for name, (handle, _keep) in out.items()}
    for handle, _keep in out.values():
        lib.tt_bank_free(handle)


def native_layer(lib, banks, layer, seed: int, sr: int) -> np.ndarray:
    pieces = np.ascontiguousarray(layer.pieces, np.float64)
    joins = np.ascontiguousarray(layer.joins, np.int32)
    f0 = np.ascontiguousarray(layer.f0, np.float64)
    out, n = POINTER(c_double)(), c_int32()
    status = lib.tt_render_spoken(banks[layer.bank], pieces.ctypes.data_as(POINTER(c_double)), len(pieces),
                                  joins.ctypes.data_as(POINTER(c_int32)), len(joins),
                                  f0.ctypes.data_as(POINTER(c_double)), len(f0), layer.warp, layer.breath, layer.tilt,
                                  layer.gain, seed, sr, ctypes.byref(out), ctypes.byref(n))
    assert status == 0
    y = np.ctypeslib.as_array(out, (n.value,)).copy()
    lib.tt_free(out)
    return y


@built
def test_random_keys_match(lib):
    for seed, label, index in ((0, "spoken", 0), (12345, "spoken", 3), (2 ** 63 + 7, "breath", -1), (99, "", -1)):
        expected = rng.key(seed, label) if index < 0 else rng.key(seed, label, index)
        assert lib.tt_key(seed, label.encode(), index) == expected


VOICES = [Speaker(pitch=120, tract=1.0, engine="natural"), Speaker(pitch=180, tract=1.15, breath=0.2, tilt=3500,
                                                                     engine="natural")]
LINES = ["Bem-vindo à forja, viajante!", "Você trouxe o minério que eu pedi?", "Sério?!", "Eu não sei..."]


@built
@pytest.mark.parametrize("sr", [48000, 22050])
@pytest.mark.parametrize("speaker", VOICES, ids=["male", "female"])
def test_spoken_layers_sound_the_same(lib, banks, speaker, sr):
    for text in LINES:
        voice = speaker.voice(text, "pt")
        layer, seed = voice.spoken[0], rng.key(voice.seed, "spoken", 0)
        expected = concat.render_spoken(layer, sr, seed)
        got = native_layer(lib, banks, layer, seed, sr)
        assert len(got) == len(expected), text
        assert np.max(np.abs(got - expected)) < 1e-6, text


def native_voice(lib, voice, sr: int, banks: dict | None = None, knobs: dict | None = None):
    """tt_render_voice: (status, samples or the error)."""
    names = list(banks or {})
    handles = (c_void_p * max(len(names), 1))(*[banks[n] for n in names])
    keys = (c_char_p * max(len(names), 1))(*[n.encode() for n in names])
    out, n = POINTER(c_float)(), c_int32()
    status = lib.tt_render_voice(voice if isinstance(voice, bytes) else voice.to_json().encode(),
                                 json.dumps(knobs).encode() if knobs else None, handles, keys, len(names), sr,
                                 ctypes.byref(out), ctypes.byref(n))
    if status:
        return status, lib.tt_last_error().decode()
    y = np.ctypeslib.as_array(out, (n.value,)).copy()
    lib.tt_free(out)
    return status, y


def same(lib, voice, sr, banks=None):
    status, got = native_voice(lib, voice, sr, banks)
    assert status == 0, got
    expected = render(voice, sr)
    assert len(got) == len(expected)
    return float(np.max(np.abs(got - expected)))


@built
def test_a_whole_voice_sounds_the_same(lib, banks):
    speaker = VOICES[0].but(crush=0.2, drive=1.5)
    voice = speaker.voice("[alegria] Que bom te ver! [tristeza] Mas eu preciso partir...", "pt")
    assert len(voice.spoken) == 2
    assert same(lib, voice, 48000, banks) < 1e-5


@built
@pytest.mark.parametrize("kind", list(RECIPES))
def test_every_sound_effect_sounds_the_same(lib, kind):
    """Every event once, spread across the styles: every layer and finishing step."""
    r = RECIPES[kind]
    for i, style in enumerate(r.styles):
        for event in r.events[i::len(r.styles)] or [r.events[i % len(r.events)]]:
            voice = Sfx(kind, style, species=1, size=0.3, power=0.8).voice(event)
            assert same(lib, voice, 22050) < 1e-6, (style, event)


@built
def test_creatures_and_music_sound_the_same(lib):
    for arch in ARCHETYPES:
        if arch != "chip":                                                    # chip programs: not native yet
            assert same(lib, Creature(arch, species=3).voice("attack"), 22050) < 1e-6, arch
    cue = Cue("levelup", "orchestral", seed=1)
    for t in cue.score.tracks.values():                                     # each track as Track.render builds it
        groups = {}
        for layer in t.layers:
            groups.setdefault({Syllable: "syllables", Modal: "modal", Noise: "noise", Scatter: "scatter"}[type(layer)],
                              []).append(layer)
        voice = Voice(**groups, seed=rng.key(cue.score.seed, t.name) & 0x7FFFFFFF, **t.voice)
        assert same(lib, voice, 22050) < 1e-6, t.name


@built
def test_the_eras_sound_the_same(lib):
    for era in ("hd", "16bit"):
        for kind, style, event in (("blade", "steel", "clash"), ("ui", "crystal", "confirm"),
                                   ("ambience", "rain", "loop")):
            voice = Sfx(kind, style, species=3, power=0.8, era=era).voice(event)
            assert same(lib, voice, 22050) < 1e-6, (era, kind)


@built
def test_a_game_turns_the_knobs_as_python_does(lib):
    """The knobs over a ready spec (native) against Python designing the sound with them."""
    for kind, style, event in (("ui", "crystal", "confirm"), ("ui", "retro", "learn"), ("status", "fantasy", "shell"),
                               ("blade", "steel", "clash"), ("ambience", "rain", "loop")):
        plain = Sfx(kind, style, species=3, power=0.8, era="16bit")
        for k in ({"register": -1, "tempo": 1.5}, {"length": 0.6, "ring": 2.5, "sparkle": 0},
                  {"brightness": 0.7, "register": 0.25}, {"brightness": -0.8, "sparkle": 2.5, "length": 1.3}):
            status, got = native_voice(lib, plain.voice(event), 22050, knobs=k)
            assert status == 0, got
            expected = plain.but(knobs=k).render(event, 0, 22050)
            assert len(got) == len(expected) and np.max(np.abs(got - expected)) < 1e-6, (kind, event, k)
    status, why = native_voice(lib, Sfx("ui").voice("cursor"), 22050, knobs={"key": 60})
    assert status == 1 and "register" in why


@built
def test_what_it_cannot_render_it_says(lib):
    assert native_voice(lib, b"{not json", 48000) == (1, "expected '\"' in the JSON")
    status, why = native_voice(lib, Creature("chip", species=3).voice("attack"), 48000)
    assert status == 4 and "chips" in why
    status, why = native_voice(lib, VOICES[0].voice("Oi!", "pt"), 48000)
    assert status == 5 and "pt/" in why
    assert native_voice(lib, Voice(modal=[Modal(0, 0.1, [(440, 0.1, 1, 9)])]), 48000)[0] == 0   # extra numbers: fine
    status, why = native_voice(lib, b'{"noise": [{"start": 0, "dur": 0.1, "freq": [[0, 500]], "wobble": [1]}]}', 48000)
    assert status == 1 and "wobble" in why
