"""Wordless voice clips for games (barks): combat efforts, pain, death, laughs, sighs, surprise, "hmm"...

Many games are not fully voiced: their characters say a short "hyah!", "ugh", "hm?" or a laugh, in their own voice,
and the text carries the rest. A bark here is a real performance, analysed once into numbers (speech/vocoder.py,
tools/build_barks.py: pitch, spectral envelope and breathiness every 5 ms), rebuilt by our own synthesis and moved
to the speaker's voice: its pitch, vocal tract, brightness, breathiness. Nothing is generated by a model at run
time; the same speaker, kind, style and take always give the same samples.

The performances are CC0 recordings: OpenGameArt "RPG Male Adventurer", "Female RPG Voice Starter Pack" (three
voices), "Male Grunt/Yelling sounds"; Freesound CC0 laughs, giggles, sighs, gasps, "hmm", "huh", "yay"...
Measured on them: an attack shout lasts 0.15-0.35 s and is pitched far above the speaking voice, men +17 to +23
semitones (95 Hz -> 250-380 Hz), women about +10. So efforts move between voices through the shouting register
(shout_pitch), the rest (laughs, sighs, hums) with the speaking pitch.

Styles, after the games that use these clips (the clips themselves are other performances):
    grunt     wordless and breathy, short and quick (Zelda's hero)
    anime     bright, voiced, lively, a younger performer when there is one (Rune Factory)
    tactics   restrained and pressed: shorter, lower, darker (Fire Emblem)
    mmo       full shouts, longer and stronger (Final Fantasy XIV)
"""
import math

import numpy as np

from .. import rng
from ..spec import Vocoded
from .vocoder import Template, templates

EMOTES = ("attack", "attack_big", "hurt", "hurt_big", "death", "jump", "tired", "laugh", "giggle", "chuckle",
          "sigh", "gasp", "surprise", "hmm", "huh", "yes", "no", "cheer", "relief", "angry")
STYLES = ("grunt", "anime", "tactics", "mmo")
EFFORTS = ("attack", "attack_big", "hurt", "hurt_big", "death", "jump", "cheer")
# per style: semitones, formant ratio, length, added air, dB/octave, contour width, and the performers it prefers
STYLE = {
    "grunt": dict(pitch=0.0, warp=1.0, stretch=0.92, breath=0.08, tilt=0.0, swing=1.0,
                  likes={"adventurer": 0.15, "yell": 0.08}),
    "anime": dict(pitch=1.0, warp=1.04, stretch=1.0, breath=-0.25, tilt=1.0, swing=1.15,
                  likes={"cute": 0.15, "adventurer": 0.05}),
    "tactics": dict(pitch=-1.0, warp=0.98, stretch=0.88, breath=0.0, tilt=-0.8, swing=0.85,
                    likes={"mature": 0.12, "adventurer": 0.08}),
    "mmo": dict(pitch=0.5, warp=1.0, stretch=1.12, breath=0.0, tilt=0.5, swing=1.1,
                likes={"yell": 0.15, "adventurer": 0.05}),
}
# when no performer of a kind is close to the voice (no woman's big attack, no man's giggle): a related kind, stretched
# and moved (length ratio, semitones). Moving formants far is what gives a converted voice away, more than pitch.
KIN = {"attack_big": ("attack", 1.5, 1.0), "hurt_big": ("hurt", 1.4, 1.0), "giggle": ("laugh", 0.75, 4.0),
       "chuckle": ("laugh", 0.8, -2.0), "tired": ("sigh", 1.0, 0.0), "relief": ("sigh", 0.8, 2.0)}
KIN_COST = 0.25
# the speaking voice of each performer, guessed from the tract we gave it (pitch Hz)
SPEAKING = ((1.0, 115.0), (1.1, 190.0), (1.15, 210.0), (1.27, 260.0))
EFFORT = 0.85                     # how far an effort goes towards the shouting register (fitted, see shout_pitch)


def shout_pitch(pitch: float, tract: float, effort: float) -> float:
    """The pitch of an effortful voice: from the speaking pitch towards a shouting register that depends on the tract
    (~420 Hz for an adult male tract, higher for shorter ones). Fitted on the recordings: a 95 Hz man shouts at
    ~345 Hz (+22 st), women speaking at 230 / 280 / 550 Hz at ~430 / 530 / 600 Hz."""
    register = 420.0 * tract ** 1.8
    return pitch ** (1 - effort) * max(register, pitch * 1.3) ** effort


def speaking_pitch(tract: float) -> float:
    t, p = zip(*SPEAKING, strict=True)
    return float(np.interp(tract, t, p))


def moves(speaker, t: Template, kind: str) -> tuple[float, float]:
    """Pitch and formant ratios that take a performer's clip to the speaker's voice."""
    own = speaking_pitch(t.tract)
    if kind in EFFORTS:
        e = EFFORT * (0.65 if kind == "jump" else 1.0)
        pitch = shout_pitch(speaker.pitch, speaker.tract, e) / shout_pitch(own, t.tract, e)
    else:
        pitch = speaker.pitch / own
    return pitch, speaker.tract / t.tract


def candidates(speaker, kind: str, style: str) -> list[tuple[float, Template, float, float]]:
    """(cost, clip, length ratio, semitones) for the clips of a kind (and its kin), best first: the least pitch and
    above all the least tract to move, the performers the style prefers."""
    kin, stretch, semis = KIN.get(kind, (None, 1.0, 0.0))
    out = []
    for t in templates():
        if t.kind not in (kind, kin):
            continue
        pitch, warp = moves(speaker, t, kind)
        cost = abs(math.log(pitch)) + 3.0 * abs(math.log(warp)) - STYLE[style]["likes"].get(t.voice, 0.0)
        if style == "tactics":
            cost += 0.2 * t.duration
        if t.kind == kind:
            out.append((cost, t, 1.0, 0.0))
        else:
            out.append((cost + KIN_COST + abs(semis) / 24, t, stretch, semis))
    return sorted(out, key=lambda c: (c[0], c[1].name))


def emote(speaker, kind: str, style: str = "grunt", intensity: float = 0.7, take: int = 0) -> Vocoded:
    """One bark in `speaker`'s voice: which clip, and how it moves."""
    if kind not in EMOTES:
        raise ValueError(f"unknown emote {kind!r}; choose from {', '.join(EMOTES)}")
    if style not in STYLES:
        raise ValueError(f"unknown style {style!r}; choose from {', '.join(STYLES)}")
    key = rng.key("emote", kind, style, repr(speaker), take)

    def u(name):
        return rng.uniform(rng.key(key, name))

    best = candidates(speaker, kind, style)
    pool = [c for c in best if c[0] <= best[0][0] + 0.25][:4]          # a take picks among the close ones
    _, t, kin_stretch, kin_semis = pool[int(u("pick") * len(pool)) % len(pool)]
    st, more = STYLE[style], float(np.clip(intensity, 0, 1)) - 0.7
    effort = kind in EFFORTS
    pitch, warp = moves(speaker, t, kind)
    semis = kin_semis + st["pitch"] + (3.0 if effort else 1.5) * more + 1.2 * (u("pitch") - 0.5)
    pitch = float(np.clip(pitch * 2 ** (semis / 12), 0.4, 2.5)) if t.pitch > 0 else 1.0
    warp = float(np.clip(warp * st["warp"], 0.75, 1.35))
    stretch = kin_stretch * st["stretch"] * (1 + (0.3 if effort else 0.2) * more) * (0.94 + 0.12 * u("stretch"))
    stretch /= math.sqrt(speaker.rate)
    breath = st["breath"] + 1.5 * max(speaker.breath - 0.05, 0.0) - (0.2 * more if effort else 0.0)
    if speaker.whisper:
        breath = max(breath, speaker.whisper)
    tilt = st["tilt"] + (2.0 if effort else 1.0) * more + 3.0 * math.log2(speaker.tilt / 3000)
    swing = st["swing"] * speaker.range ** 0.7
    return Vocoded(t.name, pitch=round(pitch, 4), warp=round(warp, 4), stretch=round(stretch, 4),
                   breath=round(float(np.clip(breath, -1, 1)), 4), tilt=round(tilt, 3), swing=round(swing, 4))
