"""Build the native core (native/): the vocoder in C++, for engines that cannot run Python (Godot first).

    python tools/build_native.py tables    # native/src/tables.hpp: the constants, from the Python reference
    python tools/build_native.py build     # native/build/tare_tune.(dll|so|dylib), for tests/test_native.py
    python tools/build_native.py godot     # the Godot extension, into native/godot/demo/bin (pip install scons)
    python tools/build_native.py demo      # the demo's voice banks and a dialogue planned in Python

The constants are written as exact hexadecimal floats, so the port uses the very numbers numpy computed. The build
needs a C++17 compiler (g++ or clang++; $CXX picks another); the Godot extension, what godot-cpp builds with (on
Windows, the Visual Studio build tools).
"""
import json
import os
import platform
import re
import subprocess
import sys
from pathlib import Path

import numpy as np

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT / "src"))
from tare.tools.tune.speech.vocoder import ap_freqs, band_freqs  # noqa: E402

NATIVE = ROOT / "native"
LIBRARY = {"Windows": "tare_tune.dll", "Darwin": "libtare_tune.dylib"}.get(platform.system(), "libtare_tune.so")
GODOT_CPP, GODOT_CPP_TAG = NATIVE / "godot" / "godot-cpp", "godot-4.5-stable"   # runs on Godot 4.5 and later
DEMO = NATIVE / "godot" / "demo"
DIALOGUE = [("Ferreiro", "m", "Bem-vindo à forja, viajante!"),
            ("Viajante", "f", "Preciso de uma espada nova. A minha quebrou na ponte."),
            ("Ferreiro", "m", "Na ponte?! Você enfrentou o troll sozinha?"),
            ("Viajante", "f", "[tristeza] Não tive escolha... ele levou o meu irmão."),
            ("Ferreiro", "m", "[raiva] Aquele monstro! Leve esta espada, e traga o garoto de volta.")]


def _array(name: str, values) -> str:
    items = ", ".join(float(v).hex() for v in values)
    return f"inline constexpr double {name}[{len(values)}] = {{{items}}};\n"


def tables():
    dc = {}
    for nfft in (1024, 2048):                     # vocoder.synthesize: the window that takes the DC out of a pulse
        w = np.hanning(nfft // 2)
        dc[nfft] = w / w.sum()
    text = ("// Generated by tools/build_native.py from the Python reference (src/tare/tools/tune/speech/vocoder.py).\n"
            "// Do not edit: run `python tools/build_native.py tables`.\n#pragma once\n\nnamespace tune {\n\n"
            + _array("BAND_FREQS_32", band_freqs(32)) + _array("BAND_FREQS_64", band_freqs(64))
            + _array("LOG_AP_FREQS", np.log(ap_freqs())) + _array("DC_1024", dc[1024]) + _array("DC_2048", dc[2048])
            + "\n}  // namespace tune\n")
    (NATIVE / "src/tables.hpp").write_text(text, encoding="utf-8")
    print(f"-> {NATIVE / 'src/tables.hpp'}")


def build():
    out = NATIVE / "build" / LIBRARY
    out.parent.mkdir(exist_ok=True)
    cmd = [os.environ.get("CXX", "g++"), "-std=c++17", "-O2", "-shared", "-fPIC", "-ffp-contract=off",
           "-DPOCKETFFT_NO_MULTITHREADING", "-DTARE_TUNE_BUILD", f"-I{NATIVE / 'include'}",
           f"-I{NATIVE / 'third_party'}", *map(str, sorted((NATIVE / "src").glob("*.cpp"))), "-o", str(out)]
    if platform.system() == "Windows":
        cmd += ["-static", "-static-libgcc", "-static-libstdc++"]      # one DLL, nothing else to ship
    subprocess.run(cmd, check=True)
    print(f"-> {out}")


def godot(target: str = "template_debug"):
    if not GODOT_CPP.exists():
        subprocess.run(["git", "clone", "--depth", "1", "--branch", GODOT_CPP_TAG,
                        "https://github.com/godotengine/godot-cpp", str(GODOT_CPP)], check=True)
    subprocess.run([sys.executable, "-m", "SCons", "-C", str(NATIVE / "godot"), f"target={target}",
                    "disable_exceptions=no", f"-j{os.cpu_count() or 2}"], check=True)   # pocketfft throws


def demo():
    from tare.tools.tune.speech import Speaker, concat, tvb
    (DEMO / "voices").mkdir(exist_ok=True)
    (DEMO / "lines").mkdir(exist_ok=True)
    for name in concat.banks("pt"):
        print(tvb.export(name, DEMO / "voices" / f"{name.replace('/', '_')}.tvb"))
    voices = {"m": Speaker(pitch=110, tract=1.0, engine="natural"),
              "f": Speaker(pitch=200, tract=1.15, engine="natural")}
    index = []
    for i, (who, voice, text) in enumerate(DIALOGUE):
        (DEMO / "lines" / f"{i:02d}.json").write_text(voices[voice].voice(text, "pt").to_json(), encoding="utf-8")
        index.append({"speaker": who, "text": re.sub(r"\[[^\]]*\]\s*", "", text), "spec": f"{i:02d}.json"})
    (DEMO / "lines" / "dialogue.json").write_text(json.dumps(index, ensure_ascii=False, indent=1), encoding="utf-8")
    print(f"-> {DEMO / 'lines'}: {len(index)} lines")


if __name__ == "__main__":
    {"tables": tables, "build": build, "godot": godot, "demo": demo}[sys.argv[1]](*sys.argv[2:])
